
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "John Smith",
    "email": "js@j.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "18597e65-2b8c-4e7f-bee8-beb3e96f9016"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "bcea8ac9-dc81-4dfd-883d-f7e8274f758f",
    "account_id_to": "bd604735-bcfc-43ff-a5c7-7396addadc52",
    "amount": 100       
}

### 

GET http://localhost:3003/balances/bcea8ac9-dc81-4dfd-883d-f7e8274f758f HTTP/1.1